package com.ei.utote.ToteLinkUpdateService;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-07-11T17:35:51.556-04:00
 * Generated source version: 2.7.16
 * 
 */
@WebService(targetNamespace = "http://schema.unitedtote.com/ToteLink/2008/06/PubSub", name = "ToteLinkUpdate")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ToteLinkUpdate {

    @WebMethod(operationName = "StatusNotification", action = "http://schema.unitedtote.com/ToteLink/2008/06/PubSub/StatusNotification")
    @Oneway
    public void statusNotification(
        @WebParam(partName = "parameters", name = "StatusChange", targetNamespace = "http://schema.unitedtote.com/ToteLink/2008/06/PubSub")
        StatusChange parameters
    );

    @WebMethod(operationName = "UpdateNotification", action = "http://schema.unitedtote.com/ToteLink/2008/06/PubSub/UpdateNotification")
    @Oneway
    public void updateNotification(
        @WebParam(partName = "parameters", name = "Updates", targetNamespace = "http://schema.unitedtote.com/ToteLink/2008/06/PubSub")
        Updates parameters
    );
}
