
package com.ei.utote.ToteLinkUpdateService;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-07-11T17:35:51.561-04:00
 * Generated source version: 2.7.16
 * 
 */
 
public class ToteLinkUpdate_ToteLinkUpdateSOAP_Server{

    protected ToteLinkUpdate_ToteLinkUpdateSOAP_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ToteLinkUpdateImpl();
        String address = "http://esb1.rtwbeta.com";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ToteLinkUpdate_ToteLinkUpdateSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
